// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import { defineConfig } from '@prisma/config';

export default defineConfig({
  datasource: {
    // Жестко зашиваем строку в конфиг самого генератора Призмы
    url: 'postgresql://neondb_owner:npg_pTmEyo3F7DiM@ep-steep-smoke-algkp36f-pooler.c-3.eu-central-1.aws.neon.tech/neondb?sslmode=require',
  },
});
