import type { Metadata } from 'next';
import { Geist, Geist_Mono } from 'next/font/google';
import './globals.css';
import { Toaster } from '@/components/ui/sonner';

const geistSans = Geist({
  variable: '--font-geist-sans',
  subsets: ['latin'],
});

const geistMono = Geist_Mono({
  variable: '--font-geist-mono',
  subsets: ['latin'],
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      suppressHydrationWarning
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
    >
      <body
        suppressHydrationWarning
        className="h-screen flex flex-row overflow-hidden"
      >
        <main className="flex-1 overflow-y-auto bg-brand-bgMain-pages">
          {children}
        </main>

        <Toaster
          position="bottom-right"
          toastOptions={{
            classNames: {
              toast: 'border-1',
              // success
              success: 'bg-emerald-50 border-emerald-500 text-emerald-700',
              // error
              error: 'bg-destructive border-destructive text-destructive',
              title: 'font-bold text-lg',
              icon: 'scale-150',
            },
          }}
        />
      </body>
    </html>
  );
}
